//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjMVC_Aula5
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUTO
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<int> IdFabricante { get; set; }
    
        public virtual TB_FABRICANTE TB_FABRICANTE { get; set; }
    }
}
